-- Crystal Maciel Nails — backend schema (generated, do not hand-edit)
-- Run once in Supabase SQL Editor. Safe to re-run: seeds only fill empty tables.

create table if not exists services(id text primary key, data jsonb not null);
create table if not exists gallery(id text primary key, data jsonb not null);
create table if not exists testimonials(id text primary key, data jsonb not null);
create table if not exists bookings(id text primary key, data jsonb not null, created_at timestamptz default now());
create table if not exists kv("key" text primary key, value jsonb not null);
create table if not exists events(id bigserial primary key, type text not null, day text not null, created_at timestamptz default now());

alter table services enable row level security;
alter table gallery enable row level security;
alter table testimonials enable row level security;
alter table bookings enable row level security;
alter table kv enable row level security;
alter table events enable row level security;
-- no public policies: only the service_role key (used by /api/*) can read/write

insert into services(id,data) values('s1','{"id":"s1","cat":"Manicure","price":55,"priceNote":"","dur":60,"name":{"en":"Signature Manicure","es":"Manicura Signature"},"desc":{"en":"Precision shaping, cuticle detailing, massage and your choice of premium polish.","es":"Limado de precisión, detalle de cutícula, masaje y tu esmalte premium favorito."}}'::jsonb) on conflict(id) do nothing;
insert into services(id,data) values('s2','{"id":"s2","cat":"Manicure","price":85,"priceNote":"","dur":75,"name":{"en":"Russian Manicure","es":"Manicura Rusa"},"desc":{"en":"Dry e-file technique for glass-smooth cuticles and weeks of flawless wear.","es":"Técnica en seco con torno para cutículas perfectas y semanas de acabado impecable."}}'::jsonb) on conflict(id) do nothing;
insert into services(id,data) values('s3','{"id":"s3","cat":"Extensions","price":95,"priceNote":"from","dur":90,"name":{"en":"Gel-X Extensions","es":"Extensiones Gel-X"},"desc":{"en":"Featherlight full-cover extensions with a natural, salon-perfect finish.","es":"Extensiones ultraligeras de cobertura total con acabado natural perfecto."}}'::jsonb) on conflict(id) do nothing;
insert into services(id,data) values('s4','{"id":"s4","cat":"Extensions","price":90,"priceNote":"from","dur":105,"name":{"en":"Acrylic Full Set","es":"Set Completo Acrílico"},"desc":{"en":"Sculpted to your ideal length and shape — strong, sharp, everlasting.","es":"Esculpidas a tu largo y forma ideal — fuertes, definidas y duraderas."}}'::jsonb) on conflict(id) do nothing;
insert into services(id,data) values('s5','{"id":"s5","cat":"Extensions","price":110,"priceNote":"from","dur":120,"name":{"en":"Sculpted Hard Gel","es":"Gel Duro Esculpido"},"desc":{"en":"Crystal-clear hard gel architecture for the most natural long-wear set.","es":"Arquitectura en gel duro para el set más natural y duradero."}}'::jsonb) on conflict(id) do nothing;
insert into services(id,data) values('s6','{"id":"s6","cat":"Pedicure","price":75,"priceNote":"","dur":75,"name":{"en":"Luxe Spa Pedicure","es":"Pedicura Spa de Lujo"},"desc":{"en":"Soak, exfoliation, callus care, massage and polish in a spa ritual.","es":"Remojo, exfoliación, cuidado de callosidades, masaje y esmaltado en un ritual de spa."}}'::jsonb) on conflict(id) do nothing;
insert into services(id,data) values('s7','{"id":"s7","cat":"Nail Art","price":25,"priceNote":"add-on","dur":20,"name":{"en":"Nail Art — Essential","es":"Arte de Uñas — Esencial"},"desc":{"en":"Minimal lines, dots, French variations and chrome accents.","es":"Líneas minimalistas, puntos, variaciones de francés y acentos cromados."}}'::jsonb) on conflict(id) do nothing;
insert into services(id,data) values('s8','{"id":"s8","cat":"Nail Art","price":60,"priceNote":"add-on","dur":45,"name":{"en":"Nail Art — Couture","es":"Arte de Uñas — Couture"},"desc":{"en":"Hand-painted miniature art, 3D elements, encapsulated details.","es":"Miniaturas pintadas a mano, elementos 3D y detalles encapsulados."}}'::jsonb) on conflict(id) do nothing;
insert into services(id,data) values('s9','{"id":"s9","cat":"Care","price":35,"priceNote":"","dur":30,"name":{"en":"Soak-Off & Repair","es":"Retiro y Reparación"},"desc":{"en":"Gentle, damage-free removal plus nail rehab and strengthening.","es":"Retiro suave sin daño, rehabilitación y fortalecimiento de la uña."}}'::jsonb) on conflict(id) do nothing;
insert into gallery(id,data) values('g1','{"id":"g1","img":"g1","tag":{"en":"Ombré","es":"Ombré"},"title":{"en":"Blush Ombré","es":"Ombré Rubor"}}'::jsonb) on conflict(id) do nothing;
insert into gallery(id,data) values('g2','{"id":"g2","img":"g2","tag":{"en":"Marble","es":"Mármol"},"title":{"en":"Noir Marble & Gold","es":"Mármol Noir y Oro"}}'::jsonb) on conflict(id) do nothing;
insert into gallery(id,data) values('g3','{"id":"g3","img":"g3","tag":{"en":"Chrome","es":"Cromo"},"title":{"en":"Rosé Chrome","es":"Cromo Rosé"}}'::jsonb) on conflict(id) do nothing;
insert into gallery(id,data) values('g4','{"id":"g4","img":"g4","tag":{"en":"Foil","es":"Foil"},"title":{"en":"Emerald & Gold Foil","es":"Esmeralda y Foil Dorado"}}'::jsonb) on conflict(id) do nothing;
insert into gallery(id,data) values('g5','{"id":"g5","img":"g5","tag":{"en":"Classic","es":"Clásico"},"title":{"en":"Rouge Stiletto","es":"Stiletto Rouge"}}'::jsonb) on conflict(id) do nothing;
insert into gallery(id,data) values('g6','{"id":"g6","img":"g6","tag":{"en":"Minimal","es":"Minimalista"},"title":{"en":"Milky Gold Line","es":"Línea Dorada Láctea"}}'::jsonb) on conflict(id) do nothing;
insert into testimonials(id,data) values('t1','{"id":"t1","name":"Sofia R.","stars":5,"text":{"en":"The most meticulous manicure I''ve ever had. Crystal doesn''t rush a single cuticle — my Russian manicure still looked fresh three weeks later.","es":"La manicura más meticulosa que he tenido. Crystal no se apresura con nada — mi manicura rusa se veía fresca tres semanas después."}}'::jsonb) on conflict(id) do nothing;
insert into testimonials(id,data) values('t2','{"id":"t2","name":"Daniela M.","stars":5,"text":{"en":"I showed her a vague idea and she painted actual art on my nails. I''ve never gotten so many compliments.","es":"Le mostré una idea vaga y pintó arte de verdad en mis uñas. Nunca había recibido tantos cumplidos."}}'::jsonb) on conflict(id) do nothing;
insert into testimonials(id,data) values('t3','{"id":"t3","name":"Priya K.","stars":5,"text":{"en":"The studio feels like a private retreat. Calm, spotless, and my Gel-X set is the most natural-looking I''ve ever worn.","es":"El estudio se siente como un refugio privado. Tranquilo, impecable, y mi set Gel-X es el más natural que he usado."}}'::jsonb) on conflict(id) do nothing;
insert into testimonials(id,data) values('t4','{"id":"t4","name":"Ashley T.","stars":5,"text":{"en":"Worth every penny. Booking online took a minute and she confirmed by text right away. I''m a client for life.","es":"Vale cada centavo. Reservar en línea tomó un minuto y me confirmó por texto de inmediato. Soy clienta de por vida."}}'::jsonb) on conflict(id) do nothing;
insert into kv("key",value) values('content','{"heroKicker":{"en":"San Fernando · Luxury Nail Atelier","es":"San Fernando · Atelier de Uñas de Lujo"},"heroT1":{"en":"Nails as","es":"Uñas como"},"heroT2":{"en":"art.","es":"arte."},"heroT3":{"en":"Luxury in","es":"Lujo en"},"heroT4":{"en":"every detail.","es":"cada detalle."},"heroSub":{"en":"Crystal Maciel crafts couture manicures — from glass-perfect Russian technique to hand-painted couture art — in an intimate private studio.","es":"Crystal Maciel crea manicuras de alta costura — desde la impecable técnica rusa hasta arte pintado a mano — en un íntimo estudio privado."},"heroCta1":{"en":"Book Appointment","es":"Reservar Cita"},"heroCta2":{"en":"Explore Services","es":"Ver Servicios"},"aboutKicker":{"en":"Meet the Artist","es":"Conoce a la Artista"},"aboutT1":{"en":"Hi, I''m","es":"Hola, soy"},"aboutT2":{"en":"Crystal.","es":"Crystal."},"aboutP1":{"en":"For nearly a decade I''ve treated nails as tiny canvases — blending European precision techniques with bold, modern artistry. My private San Fernando studio is designed as a retreat: one client at a time, unhurried, and entirely about you.","es":"Durante casi una década he tratado las uñas como pequeños lienzos — combinando técnicas europeas de precisión con un arte moderno y audaz. Mi estudio privado en San Fernando está diseñado como un refugio: una clienta a la vez, sin prisa y todo sobre ti."},"aboutP2":{"en":"I specialize in Russian e-file manicures, Gel-X extensions, and hand-painted couture nail art. Every set is customized to your hands, your style, and your life.","es":"Me especializo en manicura rusa con torno, extensiones Gel-X y arte de uñas de alta costura pintado a mano. Cada set se personaliza según tus manos, tu estilo y tu vida."},"aboutRole":{"en":"Founder & Master Nail Artist","es":"Fundadora y Maestra en Uñas"},"aboutBullets":[{"en":"Russian e-file technique for glass-smooth cuticles","es":"Técnica rusa con torno para cutículas perfectas"},{"en":"Premium, hypoallergenic products only","es":"Solo productos premium e hipoalergénicos"},{"en":"Hand-painted art — no stickers, no shortcuts","es":"Arte pintado a mano — sin calcomanías ni atajos"},{"en":"Private studio — one client at a time","es":"Estudio privado — una clienta a la vez"}],"address":"811 San Fernando Rd. Ste. 201, San Fernando, CA 91340","phone":"(747) 214-1272","phoneHref":"tel:+17472141272","hours":[{"d_en":"Tuesday – Saturday","d_es":"Martes – Sábado","t":"10:00 AM – 7:00 PM"},{"d_en":"Sunday","d_es":"Domingo","t":"11:00 AM – 5:00 PM"},{"d_en":"Monday","d_es":"Lunes","t":"Closed"}],"stats":{"years":"8","sets":"12k+","rating":"5.0"},"mapUrl":"https://www.google.com/maps/search/?api=1&query=811+San+Fernando+Rd+Ste+201+San+Fernando+CA+91340","footerTag":{"en":"Couture nails, crafted one client at a time in the heart of San Fernando.","es":"Uñas de alta costura, creadas una clienta a la vez en el corazón de San Fernando."}}'::jsonb) on conflict("key") do nothing;
insert into kv("key",value) values('settings','{"chatbot":true,"booking":true,"gallery":true,"testimonials":true}'::jsonb) on conflict("key") do nothing;
insert into kv("key",value) values('auth','{"salt":"f575dbb2e9b2db855f5d20b46d0c9bee","hash":"b802f5476653f1382b756915fcfb0c93a54ff0ba7cfd294b83e595f0ad930eddebc5e76e15695a152cb87efe3cabd3d459d7e44539ca8ef43feed5ed1519324b"}'::jsonb) on conflict("key") do nothing;
